def check_csl(xml: str, /) -> str | None: ...
def reference(entries: str, style: str, /) -> str: ...
def biblatex_to_hayagriva(bib: str, /) -> str: ...

__all__ = ["check_csl", "reference", "biblatex_to_hayagriva"]
