import { LineChart, type LineSeriesOption } from 'echarts/charts'
import {
  GridComponent,
  type GridComponentOption,
  LegendComponent,
  type LegendComponentOption,
  TitleComponent,
  type TitleComponentOption,
  ToolboxComponent,
  type ToolboxComponentOption,
  TooltipComponent,
  type TooltipComponentOption,
} from 'echarts/components'
import * as echarts from 'echarts/core'
import { UniversalTransition } from 'echarts/features'
import { CanvasRenderer } from 'echarts/renderers'
import ReactEChartsCore from 'echarts-for-react/lib/core'
import { useEffect, useRef } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import type { Category, HistoryRecord } from './types'

echarts.use([
  TitleComponent,
  ToolboxComponent,
  TooltipComponent,
  GridComponent,
  LegendComponent,
  LineChart,
  CanvasRenderer,
  UniversalTransition,
])

type EChartsOption = echarts.ComposeOption<
  | TitleComponentOption
  | ToolboxComponentOption
  | TooltipComponentOption
  | GridComponentOption
  | LegendComponentOption
  | LineSeriesOption
>

const overlayLineName = {
  n_entries: '示例文献总数',
  n_diff: '差异文献数量',
}

function buildSeries(
  records: HistoryRecord[],
  categories: Category[],
): LineSeriesOption[] {
  // Build stacked area chart form diff_counts
  const diff_counts: LineSeriesOption[] = categories.map((name) => {
    const data = records.map((r) => [r.date, r.output.diff_counts[name] ?? 0])
    return {
      name,
      type: 'line',
      stack: 'Total',
      areaStyle: {
        opacity: 0.4,
      },
      lineStyle: { width: 0 },
      showSymbol: false,
      emphasis: {
        focus: 'series',
      },
      data,
    }
  })

  // Build overlay lines from n_entries and n_diff
  const n_entries: LineSeriesOption = {
    name: overlayLineName.n_entries,
    type: 'line',
    lineStyle: { type: 'dashed', width: 3 },
    showSymbol: false,
    data: records.map((r) => [r.date, r.output.n_entries]),
  }
  const n_diff: LineSeriesOption = {
    name: overlayLineName.n_diff,
    type: 'line',
    color: 'red',
    data: records.map((r) => ({
      value: [r.date, r.output.n_diff],
      name: r.label,
    })),
    label: {
      show: true,
      formatter: (params) => params.name,
      backgroundColor: 'white',
      borderColor: 'black',
      borderWidth: 1,
      borderRadius: 4,
      padding: 4,
      position: 'top',
    },
  }

  return [...diff_counts, n_entries, n_diff]
}

function buildOption(
  records: HistoryRecord[],
  categories: Category[],
): EChartsOption {
  return {
    title: { text: 'Hayagriva GB Tracking' },
    tooltip: {
      trigger: 'axis',
      axisPointer: {
        type: 'cross',
        label: { backgroundColor: '#6a7985' },
      },
      formatter: (rawParams) => {
        const params = rawParams as unknown as {
          axisValueLabel: string
          data: [string, number]
          seriesName: string
          marker: string // HTML
        }[]

        const dateDisplay = params[0].axisValueLabel
        const date = params[0].data[0]
        const record = records.find((r) => r.date === date) as HistoryRecord
        const label = record.label ?? date

        const counts = Object.values(record.output.diff_counts)
        counts.sort((a, b) => a - b)
        const significantThreshold = counts[Math.floor(counts.length / 2)] ?? 1

        return renderToStaticMarkup(
          <div>
            <div>
              {label} — {dateDisplay}
            </div>
            <div
              style={{
                display: 'grid',
                gridTemplateColumns: 'auto 1fr',
                columnGap: '1em',
              }}
            >
              {params
                // omit overlay lines
                .filter(
                  (item) =>
                    !Object.values(overlayLineName).includes(item.seriesName),
                )
                .flatMap((item) => {
                  const level =
                    item.data[1] > 0
                      ? item.data[1] > significantThreshold
                        ? 'significant'
                        : 'normal'
                      : 'zero'
                  const color = level === 'zero' ? 'lightgray' : 'unset'
                  const fontWeight = level === 'significant' ? 'bold' : 'normal'

                  return [
                    <div key={`${item.seriesName}-label`}>
                      <span
                        // biome-ignore lint/security/noDangerouslySetInnerHtml: item.marker is generated by echarts
                        dangerouslySetInnerHTML={{ __html: item.marker }}
                      ></span>{' '}
                      <span style={{ color, fontWeight }}>
                        {item.seriesName}
                      </span>
                    </div>,
                    <div
                      key={`${item.seriesName}-value`}
                      style={{ textAlign: 'right', color, fontWeight }}
                    >
                      {item.data[1]}
                    </div>,
                  ]
                })}
            </div>
            <div>
              差异文献占 {record.output.n_diff} / {record.output.n_entries} ≈{' '}
              {((record.output.n_diff / record.output.n_entries) * 100).toFixed(
                0,
              )}
              %
            </div>
          </div>,
        )
      },
    },
    grid: {
      left: '3%',
      right: '15%', // For legends
      top: '10%',
      bottom: '10%',
    },
    legend: {
      orient: 'vertical',
      right: '3%',
      top: '15%',
    },
    toolbox: {
      feature: { saveAsImage: {} },
    },
    xAxis: [{ type: 'time', splitArea: { show: true } }],
    yAxis: [{ type: 'value' }],
    series: buildSeries(records, categories),
  }
}

export default function Chart({
  categories,
  records,
  onSelect,
}: {
  categories: Category[]
  records: HistoryRecord[]
  onSelect: (recordIndex: number) => void
}): JSX.Element {
  const chartRef = useRef<InstanceType<typeof ReactEChartsCore>>(null)

  const option = buildOption(records, categories)

  // Select the last record on start.
  // Switch to the record focused by the tooltip when clicking the chart, no matter the click hits a target or not.
  const tooltipFocus = useRef<number>(records.length - 1)
  const onShowTip = (params: { dataIndex: number }) => {
    tooltipFocus.current = params.dataIndex
  }
  useEffect(() => {
    if (chartRef.current !== null) {
      const chart = chartRef.current.getEchartsInstance()
      // https://echarts.apache.org/handbook/zh/concepts/event#监听“空白处”的事件
      chart.getZr().on('click', () => onSelect(tooltipFocus.current))
    }
  }, [onSelect])

  return (
    <ReactEChartsCore
      ref={chartRef}
      echarts={echarts}
      option={option}
      onEvents={{ showTip: onShowTip }}
      style={{
        margin: 'auto',
        width: '90%',
        height: '80vh',
      }}
    />
  )
}
